- id: changelog-version
  name: Changelog Version Bump
  description: Update version and changelog using cursor-agent AI
  entry: changelog-version
  language: python
  stages: [commit-msg]
  pass_filenames: false
  always_run: true

- id: auto-tag
  name: Auto Tag
  description: Create git tag based on version in pyproject.toml
  entry: auto-tag
  language: python
  stages: [post-commit]
  pass_filenames: false
  always_run: true

